version: '3.9'
services:
  traefik:
    image: traefik:v2.6.1
    volumes:
      - './traefik.yml:/etc/traefik/traefik.yml'
      - '/var/run/docker.sock:/var/run/docker.sock'
    ports:
      - "80:80"
      - "8080:8080"
    container_name: traefik

  nodered1:
    image: nodered/node-red
    volumes: 
      - "./myNodeREDdata:/data"
    ports:
      - "1880:1880"
    depends_on:
      - traefik
    container_name: node1

  nodered2:
    image: nodered/node-red
    volumes: 
      - "./myNodeREDdata:/data"
    ports:
      - "1880:1880"
    depends_on:
      - traefik
    container_name: node2

  nodered3:
    image: nodered/node-red
    volumes: 
      - "./myNodeREDdata:/data"
    ports:
      - "1880:1880"
    depends_on:
      - traefik
    container_name: node3